### ISSUE TITLE
pop-up

### ISSUE THREAD

**Issue by sahilNaran** [jaredrummler/MaterialSpinner#26]
I am having this issue where if the material spinner is at the bottom of the screen the options are not getting displayed because their is no screen space. How do I make it "drop-up" / "pop-up"so that all my items are shown?
Thank you!

**Comment by toledorobson** [comment]
Same problem.

**Comment by jaredrummler** [comment]
5d409eebd728c6b210bcd7f6e9707d0ad914349e should fix this

**Comment by toledorobson** [comment]
@jaredrummler

Still when the spinner is on the bottom, the spinner becomes useless. It displays items on the down.

**Comment by abhriyaroy** [comment]
The problem of the drop down menu being shown downwards when the spinner is at the bottom, still persists. Please help.

**Comment by sahilNaran** [comment]
It has been a year already since this issue was created. Sorry @jaredrummler but I would consider this library dead.

**Comment by jaredrummler** [comment]
I'm sorry I haven't had enough time to look into this. Pull requests are welcome.

> Number 1 rule of open source hobby projects (that not enough people follow): never let anyone dictate what you spend time on but you.

- @JakeWharton 
https://twitter.com/JakeWharton/status/907751676131639298

**Comment by sahilNaran** [comment]
Thanks, I agree with that, I understand what you are saying. I apologise.

**Comment by jaredrummler** [comment]
I added the MaterialSpinner to the bottom of the layout and can't reproduce the described behavior.

![GIF](https://i.imgur.com/1DkplPp.gif)

**Comment by sahilNaran** [comment]
My app that used the spinner is now dead, but there is another issue describing the same behaviour: https://github.com/jaredrummler/MaterialSpinner/issues/64

**Comment by jaredrummler** [comment]
If you, @zephyo, or someone else could please provide an example project that reproduces the issue I will look into this.

**Comment by abhriyaroy** [comment]
Hi @jaredrummler I have added a sample project here https://github.com/abhriyaroy/MyApplication please check it out.
Also here are the screenshots -
1) Initially when both the spinners are closed https://i.imgur.com/6oUVCJz.png
2) When the default android spinner is expanded https://i.imgur.com/EpyoYTR.png
3) When MaterialSpinner is expanded https://i.imgur.com/q55RWQ2.png

Thank you so much.

**Comment by abhriyaroy** [comment]
That solved the issue. Thank you so much.

**Comment by zephyo** [comment]
Woo! Thank you!
