### ISSUE TITLE
I want to display spinner dropdown to above spinner view when spinner is at the bottom of the screen

### ISSUE THREAD

**Issue by ShraddhaGadesha** [jaredrummler/MaterialSpinner#37]
I have implemented betterspinner in my project.
In one screen spinner is at the bottom of the screen
when I click on spinner dropdown is displaying at bottom I want to display it above spinner view same as Spinner for android .
Pls help

**Comment by Gira-X** [comment]
I have the same bug occurring on devices running API26 (see picture below), while it works on API16.

I fixed it by modifying the `expand()` from:

```java
public void expand() {
	if (!hideArrow) {
		animateArrow(true);
	}
	nothingSelected = true;
	if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
		popupWindow.setOverlapAnchor(false);
		popupWindow.showAsDropDown(this);
	} else {
		int[] location = new int[2];
		getLocationInWindow(location);
		int x = location[0];
		int y = getHeight() + location[1];
		popupWindow.showAtLocation(this, Gravity.TOP | Gravity.START, x, y);
	}
}
```

to

```java
public void expand() {
	if (!hideArrow) {
		animateArrow(true);
	}
	nothingSelected = true;
	int[] location = new int[2];
	getLocationInWindow(location);
	int x = location[0];
	int y = getHeight() + location[1];
	popupWindow.showAtLocation(this, Gravity.TOP | Gravity.START, x, y);
}
```

@jaredrummler does my fix break anything else?
So far I have not noticed any issues with it.

![image](https://user-images.githubusercontent.com/15002298/27898285-973de854-6225-11e7-9ccf-0d343f5c1da6.png)

**Comment by youssefshamass** [comment]
Still facing the same issue in API 28, using the latest version of the library
